spring.application.name=Biblio-API

spring.datasource.url=jdbc:postgresql://localhost:5432/tfg
spring.datasource.username=postgres
spring.datasource.password=607235252
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
